### ISSUE TITLE
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-q3zIM5/feedparser/

### ISSUE THREAD

**Issue by Jo-won** [GzuPark/prarxivate#22]
If you find this error,  
![image](https://user-images.githubusercontent.com/46413594/69687150-39c5e280-1105-11ea-8a68-111604086eff.png)

pls, **pip install --upgrade setuptools**

and if you find this error after that

![image](https://user-images.githubusercontent.com/46413594/69687211-75f94300-1105-11ea-894b-0f393faed79f.png)

pls, **pip install wheel**

reference : https://github.com/facebook/prophet/issues/418

**Comment by GzuPark** [comment]
Recommend to use Python >= 3.6 version.
I will record this issue at the archived issues file.
